# Generated by Django 4.1.7 on 2023-03-25 06:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("APP", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="legos",
            name="total",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
