# Generated by Django 4.1.7 on 2023-03-31 14:36

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("APP", "0006_register"),
    ]

    operations = [
        migrations.DeleteModel(
            name="register",
        ),
    ]
